services:

  # App server
  app:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_API_KEY: ${SUPABASE_API_KEY}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      # Expose server's port to host
      - "${SERVER_PORT}:9000"
    volumes:
      # Mount the current dir to /app for live updates
      - .:/app
    # healthcheck:
        # Verify FastAPI endpoints are accessible
    #   test: ["CMD-SHELL", "curl --silent --fail http://localhost:9000/health || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5 // Add /health to API endpoints for backend service health check.
    networks:
      # Connect container to 'newsalyzer-network'
      - newsalyzer-network

# Define named volumes
volumes:
  db_data:

# Define network
networks:
  newsalyzer-network:
    driver: bridge
