services:

  # App server
  app:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_API_KEY: ${SUPABASE_API_KEY}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      # Expose server's port to host
      - "${SERVER_PORT}:9000"
    volumes:
      # Mount the current dir to /app for live updates
      - .:/app
    healthcheck:
      # Verify FastAPI endpoints are accessible
      test: ["CMD-SHELL", "curl --fail --max-time 10 --write-out '%{http_code}\n' --output /dev/stdout http://app:9000/health | grep -q '200' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      # Connect container to 'newsalyzer-network'
      - newsalyzer-network

# Define named volumes
volumes:
  db_data:

# Define network
networks:
  newsalyzer-network:
    driver: bridge
