name: Newsalyzer CI/CD Pipeline

on:
  push:
    branches:
      - main
      - '*-implementation'
      - '*-integration'
      - 'fix-*'
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy-docker-image:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      LOG_LEVEL: DEBUG

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        
      - name: Set up virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install requirements
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/newsalyzer:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/newsalyzer:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/newsalyzer:cache,mode=max
      
      - name: Set up Docker compose and create .env
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env
          echo "SUPABASE_API_KEY=${{ secrets.SUPABASE_API_KEY }}" >> .env
          echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env
          echo "LOG_LEVEL=INFO" >> .env

      - name: Create logs directory and set permissions
        run: |
          mkdir -p /home/runner/work/newsalyzer/newsalyzer/logs
          chmod -R 777 /home/runner/work/newsalyzer/newsalyzer/logs

      - name: Start services
        run: |
          docker-compose up -d
          sleep 30

      - name: Check FastAPI health
        run: |
          timeout 120s bash -c 'until curl --fail --max-time 10 http://localhost:${{ secrets.SERVER_PORT }}/health; do
            echo "Waiting for service to become healthy..."
            sleep 5
          done'
      
      - name: (failure only) Display FastAPI app logs
        if: ${{ failure() }}
        run: |
          echo "FastAPI app logs:"
          docker-compose logs app

      - name: (failure only) Display all custom logs
        if: ${{ failure() }}
        run: |
          echo "Custom logs:"
          ls -l logs
          tail -n 100 logs/*

      - name: Run API tests
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)
          pytest -c config/pytest.ini tests/api_tests.py
      
      - name: Stop docker services
        run: |
          docker-compose down --volumes --remove-orphans --timeout 30
